// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2EHjb_T1nBYH_84bf8USu3WtXac99GK8',
    appId: '1:1096820538152:web:043eebf6ecfac27143ae1d',
    messagingSenderId: '1096820538152',
    projectId: 'ceylona-a096f',
    authDomain: 'ceylona-a096f.firebaseapp.com',
    storageBucket: 'ceylona-a096f.firebasestorage.app',
    measurementId: 'G-E5LL36GLKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATm3xmVAkhL3-VyUFSFrPSrKDu32pC8v0',
    appId: '1:1096820538152:android:f32b5af623617df843ae1d',
    messagingSenderId: '1096820538152',
    projectId: 'ceylona-a096f',
    storageBucket: 'ceylona-a096f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqtQ0SHk0PseRwoK4ODTjIgpIBvhp1vH0',
    appId: '1:1096820538152:ios:fa9ae6ecec1ed9a143ae1d',
    messagingSenderId: '1096820538152',
    projectId: 'ceylona-a096f',
    storageBucket: 'ceylona-a096f.firebasestorage.app',
    iosBundleId: 'com.example.ceylona',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqtQ0SHk0PseRwoK4ODTjIgpIBvhp1vH0',
    appId: '1:1096820538152:ios:fa9ae6ecec1ed9a143ae1d',
    messagingSenderId: '1096820538152',
    projectId: 'ceylona-a096f',
    storageBucket: 'ceylona-a096f.firebasestorage.app',
    iosBundleId: 'com.example.ceylona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2EHjb_T1nBYH_84bf8USu3WtXac99GK8',
    appId: '1:1096820538152:web:01412410f9b9790543ae1d',
    messagingSenderId: '1096820538152',
    projectId: 'ceylona-a096f',
    authDomain: 'ceylona-a096f.firebaseapp.com',
    storageBucket: 'ceylona-a096f.firebasestorage.app',
    measurementId: 'G-P9KQ005TXN',
  );
}
